#169258575 consume signup api
andela/team-odd-bn-frontend pull request #11
Opened 2019-12-29 09:15 UTC by hezronkimutai

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-01-06 06:44 UTC, NiyongaboEric requested changes

2020-01-06 06:44 UTC, NiyongaboEric commented on src/__tests__/reducers/auth/signup.test.js
> +});
I recommend you move all mocks data such as action, actions type and reducer into dummy data directory so that in future probably we may re-use them.

2020-01-06 06:44 UTC, NiyongaboEric commented on src/assets/css/App.scss
> +  }
add EOL

2020-01-06 06:44 UTC, NiyongaboEric commented on src/assets/css/base.scss
> +}
EOL

2020-01-06 06:44 UTC, NiyongaboEric commented on src/assets/css/errors.scss
> +
EOL

2020-01-06 06:44 UTC, NiyongaboEric commented on src/components/InputField.js
> +export default InputField;
+1

2020-01-06 06:44 UTC, NiyongaboEric commented on src/components/Spinner.js
> +// };
Please remember to validate props.

2020-01-06 06:44 UTC, NiyongaboEric commented on src/components/SubmitButton.js
> +// };
Check again and make sure all props are validated.

2020-01-06 06:44 UTC, NiyongaboEric commented on src/constants/signUp.js
> +  { input: 'Last Name', className: 'lastName', type: 'text' },
Good idea. +1

2020-01-06 06:44 UTC, NiyongaboEric commented on src/redux/store/index.js
> +// const middlewarea = applyMiddleware(applyMiddleware.withClient(axios));
Why are you trying to add this line?

2020-01-06 06:46 UTC, NiyongaboEric commented
Good job @hezronkimutai! I would like to know how to test your work

This is error I am getting.
<img width="1440" alt="Screen Shot 2020-01-06 at 08 40 49" src="https://user-images.githubusercontent.com/56690376/71800385-a61af680-3060-11ea-98e0-e779fca18793.png">

2020-01-06 12:20 UTC, nziokaivy requested changes
Nice work Hezron! Please take note of the feedback

2020-01-06 12:20 UTC, nziokaivy commented on src/__tests__/actions/auth/signup.test.js
> +    await store.dispatch(signupAction({
Please move this mock data in the mock folder

2020-01-06 12:20 UTC, nziokaivy commented on src/assets/css/spinner.scss
> +
eol

2020-01-06 13:57 UTC, victorkarangwa4 commented on src/redux/actions/authActions.js
> +        type: SIGNUP_ERROR,
@hezronkimutai can you work on this try/catch block?
The feature is working properly when I provide incomplete/wrong info. However, When I provide correct information, I'm getting `network error`.

2020-01-06 13:57 UTC, victkarangwa requested changes
Nice work @hezronkimutai 
I left some feedback

2020-01-06 13:59 UTC, victorkarangwa4 commented on src/__tests__/VerifyEmail.test.js
> +describe('First React component test with Enzyme', () => {
Would you mind giving a clear description of this test suite?

2020-01-06 14:02 UTC, victorkarangwa4 commented on src/__tests__/actions/auth/signup.test.js
> +        confirmPassword: 'hezronKK',
Could you please place this information in the mock data>

2020-01-07 08:33 UTC, NiyongaboEric approved these changes

2020-01-07 09:02 UTC, william000000 approved these changes
Good Job @hezronkimutai, I really admired your work.

2020-01-07 09:02 UTC, william000000 commented on src/constants/signUp.js
> +  },
Nice Shot!

2020-01-07 13:37 UTC, nziokaivy approved these changes

2020-01-08 08:29 UTC, victkarangwa approved these changes
Good job @hezronkimutai 
I think you are good to go!

2020-01-08 10:29 UTC, shemaeric approved these changes
Good work @hezronkimutai

2020-01-08 10:29 UTC, merged