#169258576 Users should be presented with a reset password
andela/team-odd-bn-frontend pull request #12
Opened 2019-12-30 09:18 UTC by victorkarangwa4

#### What does this PR do?
This PR adds password reset link
#### Description of Task to be completed?
A user will be presented with a button and or link to reset their passwords on the SignUp/Register component
#### How should this be manually tested?
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169258576](https://www.pivotaltracker.com/story/show/169258576)
#### Screenshots (if appropriate)
#### Questions:

2020-01-06 07:59 UTC, NiyoEric requested changes
Good job @victorkarangwa4! Also, I would like to request also the following
 - Test reset password feature in production.
- Share environment variables if any
- Make table responsive.

2020-01-06 07:59 UTC, NiyoEric commented on src/__tests__/actions/resetPasswordActions.test.js
> +});
I recommend you move mock data into their own file so that another person can re-use it.

2020-01-06 07:59 UTC, NiyoEric commented on src/__tests__/reducers/resetPasswordReducer.test.js
> +});
Separate mock data from test.

2020-01-06 07:59 UTC, NiyoEric commented on src/assets/css/errors.scss
> +}
add EOL

2020-01-06 07:59 UTC, NiyoEric commented on src/assets/css/footer.scss
> +//   }
Remove comment.

2020-01-06 07:59 UTC, NiyoEric commented on src/assets/css/footer.scss
> +    position: absolute;
One property cannot have 2 positions. Please remove one.

2020-01-06 07:59 UTC, NiyoEric commented on src/assets/css/header.scss
> +  }
Indent well your style and add EOL

2020-01-06 07:59 UTC, NiyoEric commented on src/assets/css/passwordReset.scss
> +  }
Ident style and add EOL everywhere

2020-01-06 07:59 UTC, NiyoEric commented on src/assets/css/spinner.scss
> +}
EOL.

2020-01-06 07:59 UTC, NiyoEric commented on src/containers/user/password/resetPassword.js
> +        {/* {console.log('======>', stateObject.auth.resetPassword.status)} */}
Remove comment.

2020-01-06 07:59 UTC, NiyoEric commented on src/redux/reducers/authReducers/resetPasswordReducer.js
> +export default resetPasswordReducer;
Move mock data into `__mocks__` dir

2020-01-06 09:39 UTC, nziokaivy requested changes
you can try and make the reset password page more responsive 

![image](https://user-images.githubusercontent.com/45204494/71809678-3cf3ad00-3079-11ea-819f-5562dc8c7164.png)

2020-01-06 09:51 UTC, nziokaivy requested changes
Great work Victor! Nice implementation of the task just make sure the pages are responsive as well as make sure you take note of the end of line convention.

2020-01-06 10:29 UTC, hezronkimutai commented on src/__tests__/actions/resetPasswordActions.test.js
> +      }];
Hey @victorkarangwa4 , it could be convenient to put this data in the mock data

2020-01-06 10:32 UTC, hezronkimutai commented on src/components/SubmitButton.js
> +export default SubmitButton;
Remember to validate props in this component.

2020-01-06 10:41 UTC, hezronkimutai requested changes
Nice work @victorkarangwa4 , I left some changes please review them and we will be good to go.

2020-01-06 16:54 UTC, hezronkimutai approved these changes
Nice work @victorkarangwa4 , I think you are good to start the next task.

2020-01-06 20:57 UTC, victorkarangwa4 commented
> you can try and make the reset password page more responsive
> 
> ![image](https://user-images.githubusercontent.com/45204494/71809678-3cf3ad00-3079-11ea-819f-5562dc8c7164.png)

2020-01-07 08:27 UTC, NiyoEric approved these changes

2020-01-07 09:41 UTC, william000000 reviewed
Looks good to go, Nice Work@victorkarangwa4

2020-01-07 09:41 UTC, william000000 commented on src/assets/css/App.scss~9d8f0ad2c2c12e177e9fc36bc4cceac974984699
> +  }
What does this file do?

2020-01-07 13:57 UTC, william000000 approved these changes
Great Work @victorkarangwa4

2020-01-07 13:58 UTC, nziokaivy approved these changes

2020-01-09 08:08 UTC, shemaeric approved these changes
Good work @victorkarangwa4

2020-01-09 08:09 UTC, merged