ft(signIn): user login
andela/team-odd-bn-frontend pull request #13
Opened 2019-12-30 10:00 UTC by william000000

[Finishes 169258577]

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-01-06 09:08 UTC, nziokaivy reviewed
Great job @william000000! I have a few comments you could work on 

Also, work on displaying better error messages

2020-01-06 09:08 UTC, nziokaivy commented on src/containers/user/signin/signin.js
> +const actions = {
Rather than calling this actions I recommend naming it `mapDispatchToProps` which is a better naming convention

2020-01-06 09:08 UTC, nziokaivy commented on src/assets/css/base.scss
> +}
eol

2020-01-06 09:08 UTC, nziokaivy commented on src/assets/css/signin.scss
> +}
eol

2020-01-06 09:08 UTC, nziokaivy commented on src/assets/css/spinner.scss
> +
eol

2020-01-06 09:28 UTC, NiyongaboEric requested changes
Well done @william000000! I would like to request the following 
- To see how signin works on Heroku

- To work on responsiveness such that logo is not stretched and form label are visible. and make sure it support Mobile and desktop view.
<img width="1068" alt="Screen Shot 2020-01-06 at 11 12 22" src="https://user-images.githubusercontent.com/33821734/71808561-c6ee4680-3076-11ea-9c51-31c19e3e07c8.png">

- use `cursor: pointer` to every input and button.

- To increase coverage to atleast 90%
<img width="1440" alt="Screen Shot 2020-01-06 at 11 09 21" src="https://user-images.githubusercontent.com/33821734/71808871-83e0a300-3077-11ea-95bd-d4b7c56581e8.png">

2020-01-06 09:28 UTC, NiyongaboEric commented on src/__tests__/actions/auth/signin.test.js
> +});
Move mock data in `src/__mocks__` so that it looks nice and other can re-use it.

2020-01-06 09:28 UTC, NiyongaboEric commented on src/__tests__/components/InputField.test.js
> +});
Separate data and add EOL everywhere.

2020-01-06 09:28 UTC, NiyongaboEric commented on src/assets/css/base.scss
> +}
EOL

2020-01-06 17:49 UTC, hezronkimutai commented on src/__tests__/views/auth/loginView.test.js
> +      },
Put this data in the __mocks__ directory

2020-01-06 17:51 UTC, hezronkimutai commented on src/views/auth/LoginView.js
> +const { ICON } = process.env;
Hi @william000000 , You can put the Icon in the assets cz it is small.

2020-01-06 17:52 UTC, hezronkimutai requested changes
Nice work @william000000 , I left some comments, Please view  them.

2020-01-07 08:21 UTC, hezronkimutai approved these changes
Nice work @william000000 .

2020-01-07 08:53 UTC, NiyongaboEric approved these changes

2020-01-07 09:47 UTC, victorkarangwa4 commented on src/__tests__/actions/auth/signin.test.js
> +      password: 'Simulation1$',
I think email & password should be placed in the mocks

2020-01-07 09:47 UTC, victorkarangwa4 commented on src/components/Spinner.js
> +    ? (
Would you mind placing in the containers instead?

2020-01-07 12:03 UTC, victkarangwa approved these changes
Good job on implementing the feedback.

2020-01-07 13:30 UTC, shemaeric requested changes
Kindly work on requested changes @william000000

2020-01-07 13:30 UTC, shemaeric commented on src/components/Spinner.js
> +// import React from 'react';
Kindly remove the commented codes @william000000

2020-01-08 11:18 UTC, shemaeric approved these changes

2020-01-08 11:18 UTC, merged