ft(profile): Add user can be able to view and update profile function…
andela/team-odd-bn-frontend pull request #14
Opened 2019-12-31 11:16 UTC by nziokaivy

…ality

- Set up profile redux architecture
- Add view profile and edit profile components
- Add route to edit component
- Add tests
- Add styling

[Finishes #169258579]

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-01-06 08:33 UTC, NiyoEric requested changes
Good job @nziokaivy I would like to see the following
- How the feature works on Heroku
- I request to have at least 90%  coverage. 
- Make profile page responsive.
- Implement if the token is not available in local storage redirect user to sign in page. Next time token will be available and users will be able to update. 

If no token this is what would happen
<img width="1440" alt="Screen Shot 2020-01-06 at 10 24 14" src="https://user-images.githubusercontent.com/56690376/71805743-a242a080-306f-11ea-80fe-2dea9bc09982.png">

- Last, display meaningful message such as . `Picture is too big`
<img width="1440" alt="Screen Shot 2020-01-06 at 10 32 38" src="https://user-images.githubusercontent.com/56690376/71805852-f8afdf00-306f-11ea-874b-c57a1cd544fd.png">

2020-01-06 08:33 UTC, NiyoEric commented on src/__tests__/actionTests/profileActionTests.js
> +});
I recommend you move mock data from test into `src/__mocks__` so that another person may use it later.

2020-01-06 08:33 UTC, NiyoEric commented on src/__tests__/componentTests/navbarTests.js
> +});
Also, remove mock data everywhere in the test.

2020-01-06 08:33 UTC, NiyoEric commented on src/components/Navbar.js
> +    const {
Remove console.

2020-01-06 08:33 UTC, NiyoEric commented on src/components/Profile.js
> +
Remove console.

2020-01-06 08:33 UTC, NiyoEric commented on src/__tests__/componentTests/profileTests.js
> +    console.log(component.instance());
Remove console.

2020-01-06 10:13 UTC, william000000 requested changes
Good Job @nziokaivy, I would recommend use of `Spinner` in case the page is loading the data

2020-01-06 10:42 UTC, william000000 reviewed
You can also make these fields editable, for the line manager field, I suggest using `select Input` and use `GET` request to show all managers available.
![image](https://user-images.githubusercontent.com/40672143/71813194-b42d3f00-3081-11ea-8d0b-7d4fe2ce6e63.png)

2020-01-06 17:21 UTC, victkarangwa requested changes

2020-01-06 17:21 UTC, victorkarangwa4 commented on src/App.js
> +          <Route path="/profile" exact component={Profile} />
Could you please first check if the user is logged in? You can achieve this by modifying your route (if token is in the props)like this:
```js
<Route
	exact
	path='/profile'
	render={props => (token ? <profile /> : <Redirect to='/login' />)}
/>
```

2020-01-06 17:53 UTC, hezronkimutai commented on src/__tests__/actionTests/profileActionTests.js
> +        },
@nziokaivy , You can put this data in the mock data directory.

2020-01-06 17:55 UTC, hezronkimutai commented on src/__tests__/actionTests/profileActionTests.js
> +      }];
this one too, and any other data that can be placed in the mock data without complicating your work, But also there are others you can just leave it in the tests for some reasons.

2020-01-06 17:58 UTC, hezronkimutai commented on src/__tests__/reducerTests/profileReducerTests.js
> +  // });
Don't forget to remove the comments when you are done fixing the tests.

2020-01-06 18:00 UTC, hezronkimutai requested changes
Nice work @nziokaivy , I have reviewed and left some changes please have a look at them, happy hacking.

2020-01-08 09:39 UTC, hezronkimutai approved these changes

2020-01-08 11:14 UTC, NiyoEric approved these changes

2020-01-08 11:56 UTC, victkarangwa approved these changes
Nice work @nziokaivy

2020-01-08 12:45 UTC, william000000 approved these changes
Good Job @nziokaivy

2020-01-09 20:52 UTC, shemaeric requested changes
Good work @nziokaivy. But they are some changes I would like to point out:

- To update the profile, the user has to provide all the data in the input fields. I think we can give a user the option to update any data he/she wants ( for the fields that will not be updated, we will keep the data that were already there, let's say maybe I want to update only the bio).
- Align all the inputs.

2020-01-09 20:52 UTC, shemaeric commented on src/components/Profile.js
> +        //   firstName,
Please remove the commented codes. @nziokaivy

2020-01-14 20:01 UTC, shemaeric approved these changes

2020-01-14 20:01 UTC, merged