#170602242 Design landing page
andela/team-odd-bn-frontend pull request #19
Opened 2020-01-08 21:10 UTC by nziokaivy

#### What does this PR do?

Add the landing page of the application

#### Description of Task to be completed?

- Add landing page HTML layout
- Add landing page style
- Style landing page responsive mobile design

#### How should this be manually tested?

- Clone this repository using the command `git clone https://github.com/andela/team-odd-bn-frontend.git`
- Then navigate into the project `cd team-odd-bn-frontend`
- Switch to the landing page branch using the command: `git checkout ch-landing-page-170602242`
- Run the command `npm i `to install all the packages
- Run `npm run dev` to run the server which will land you to the landing page

#### Any background context you want to provide?

As a user, I would like to view the landing page that can assist in interacting with the application

#### What are the relevant pivotal tracker stories?
[#170602242](https://www.pivotaltracker.com/story/show/170602242)
#### Screenshots (if appropriate)

###### Desktop view

![image](https://user-images.githubusercontent.com/45204494/72016166-ef8b6180-326b-11ea-9870-74815b984cba.png)

###### Mobile view

![image](https://user-images.githubusercontent.com/45204494/72016203-0631b880-326c-11ea-95f2-533bc3335900.png)

#### Questions:

2020-01-09 16:39 UTC, hezronkimutai requested changes
Hi @nziokaivy , Correct the responsiveness in ipad and ipad pro then we will be good to go.

<img width="693" alt="Screen Shot 2020-01-09 at 18 37 09" src="https://user-images.githubusercontent.com/45129725/72086197-31b9af00-330f-11ea-851e-a40029208be2.png">
![Uploading Screen Shot 2020-01-09 at 18.37.24.png…]()

2020-01-10 09:02 UTC, NiyongaboEric approved these changes
Well done @nziokaivy!

2020-01-13 07:29 UTC, victkarangwa reviewed
Good job @nziokaivy 
Just attend to the feedback I left

2020-01-13 07:29 UTC, victorkarangwa4 commented on src/components/LandingPage.js
> +      <div className="main-logo">
@nziokaivy 
Is it a good idea to have inline styles?
Maybe we can place this style: `backgroundColor: 'white'` in external styles

2020-01-13 08:12 UTC, hezronkimutai approved these changes

2020-01-15 07:30 UTC, victkarangwa approved these changes
Good job @nziokaivy !

2020-01-16 10:53 UTC, shemaeric approved these changes
Good work @nziokaivy

2020-01-16 10:53 UTC, merged