feat(authentication): user should be able to verify email address
andela/team-odd-bn-frontend pull request #23
Opened 2020-01-10 00:04 UTC by victorkarangwa4

#### What does this PR do?
This PR adds email verification page after user signs up
#### Description of Task to be completed?
- A user is able to resend a verification email after signup
- A user is able to navigate directly to the app after email verification
- User is able to get a successful registration page
#### How should this be manually tested?
- `git clone https://github.com/andela/team-odd-bn-frontend.git`
- `cd team-odd-bn-frontend`
- `git checkout ft-email-verification-page-170574394`
- `npm install` packages
- `npm run dev` to start the development server
- It should open your default browser automatically
- Navigate to `localhost:4000/resend-email` to access the page directly
#### Any background context you want to provide?
Previously, the users used to validate their email using the backend part
#### What are the relevant pivotal tracker stories?
[#170574394](https://www.pivotaltracker.com/story/show/170574394)
#### Screenshots (if appropriate)
###### Resend verication email page
<img width="1440" alt="Screen Shot 2020-01-09 at 12 53 25" src="https://user-images.githubusercontent.com/35301129/72061696-133bbf80-32df-11ea-9fd5-a0fddbb5864c.png">

###### Successful email verication page
<img width="1440" alt="Screen Shot 2020-01-10 at 02 01 13" src="https://user-images.githubusercontent.com/35301129/72114743-24231a00-334d-11ea-8178-42f277a94ab8.png">

#### Questions:
N/A

2020-01-10 09:07 UTC, william000000 requested changes

2020-01-10 09:07 UTC, william000000 commented on src/containers/user/resendEmail.js
> +            </div>
It should be better when this cloudinary link comes from `.env`  instead of showing up the whole link.

2020-01-13 08:15 UTC, hezronkimutai approved these changes
Nice work @victorkarangwa4

2020-01-16 05:18 UTC, NiyongaboEric requested changes
Well done @victorkarangwa4. All test are passing and UI is responsive. However, I am not able to run your work locally.
<img width="1440" alt="Screen Shot 2020-01-16 at 07 08 06" src="https://user-images.githubusercontent.com/33821734/72495787-4ecf1000-3830-11ea-87c4-a3ee89ed3587.png">

2020-01-16 06:54 UTC, NiyongaboEric approved these changes

2020-01-16 10:34 UTC, william000000 approved these changes
@victorkarangwa4  Looks good to go!

2020-01-16 10:58 UTC, shemaeric approved these changes
Good work @victorkarangwa4

2020-01-16 11:52 UTC, merged