Ft one way trip request 170602091
andela/team-odd-bn-frontend pull request #24
Opened 2020-01-11 12:20 UTC by william000000

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-01-17 05:55 UTC, hezronkimutai commented on src/App.js
> +axios.defaults.baseURL = 'https://team-odd-bn-backend-staging.herokuapp.com/api/v1/users';
Hi @willy, put this in the .env

2020-01-17 05:56 UTC, hezronkimutai commented on src/__tests__/actionTests/profileActionTests.js
> +  //     request.respondWith({
Don't forget to remove these comments.

2020-01-17 05:56 UTC, hezronkimutai commented on src/assets/css/App.scss
> +}
eol

2020-01-17 05:57 UTC, hezronkimutai commented on src/assets/css/base.scss
> +}
add eol.

2020-01-17 05:59 UTC, hezronkimutai reviewed
Hi @william000000 , Left some comments,.

2020-01-17 08:23 UTC, NiyongaboEric requested changes
Good job @william000000. Also, ensure the following:
- Fixing test
- Ensure one way trip request works on Heroku
- Trips sidebar should not overflow the top navbar

<img width="1440" alt="Screen Shot 2020-01-17 at 10 09 41" src="https://user-images.githubusercontent.com/33821734/72595219-fb34f300-3911-11ea-9c19-2d5cb159cc83.png">

2020-01-17 10:54 UTC, hezronkimutai approved these changes
Nice job.

2020-01-17 13:32 UTC, NiyongaboEric approved these changes

2020-01-20 14:31 UTC, nziokaivy approved these changes
Great job! @Willy

2020-01-21 20:41 UTC, shemaeric approved these changes
Good work @william000000

2020-01-21 20:41 UTC, merged