Ft create accommodation facility 169258599
andela/team-odd-bn-frontend pull request #27
Opened 2020-01-16 08:04 UTC by victorkarangwa4

#### What does this PR do?
This PR adds functionality for a travel admin to create an accommodation facility for users
#### Description of Task to be completed?
- The travel admin is able to enter a name for the location/accomodation facility
- The travel admin is able to enter the location (I.E address) of the center
- The travel admin is able to upload an image of the centre 
- The travel admin is able to create a number of rooms with room names and room type
#### How should this be manually tested?
- `git clone https://github.com/andela/team-odd-bn-frontend.git`
- `cd team-odd-bn-frontend`
- `git checkout ft-create-accommodation-facility-169258599`
- `npm install` packages
- `npm run dev` to start the development server
- It should open your default browser automatically
- Navigate to `localhost:4000/accommodation/create` to access the page directly
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169258599](https://www.pivotaltracker.com/story/show/169258599)
#### Screenshots (if appropriate)
###### Adding photos
<img width="1440" alt="addPhotos" src="https://user-images.githubusercontent.com/35301129/72504432-76c96e00-3846-11ea-8fdc-42812a2b7f8d.png">

###### Adding rooms
<img width="1440" alt="addRooms" src="https://user-images.githubusercontent.com/35301129/72504435-77620480-3846-11ea-94d0-8bdbcec96f47.png">

###### creating accommodation
<img width="1439" alt="accommodation" src="https://user-images.githubusercontent.com/35301129/72504430-76c96e00-3846-11ea-8d1f-048966f8b4d4.png">

#### Questions:
N/A

2020-01-16 12:17 UTC, hezronkimutai commented on src/__mocks__/accommodation/createAccommodation.js
> +// create accommodation reducers
You can remove this comment victor

2020-01-16 12:19 UTC, hezronkimutai commented on src/__tests__/containers/accommodation/createAccommodation.test.js
> +    // component.find('[data-test="addPhotos-btn"]').simulate('click');
Remove this comment @victor.

2020-01-16 12:19 UTC, hezronkimutai commented on src/__tests__/containers/accommodation/createAccommodation.test.js
> +// });
make sure you remove all the comments

2020-01-16 14:39 UTC, hezronkimutai requested changes
Hi @victorkarangwa4 , nice job, correct the responsiveness of small screens

<img width="492" alt="Screen Shot 2020-01-16 at 16 38 52" src="https://user-images.githubusercontent.com/45129725/72533979-bb70fb80-387e-11ea-8575-97167a7d93f6.png">

2020-01-16 16:11 UTC, victorkarangwa4 commented
> Hi @victorkarangwa4 , nice job, correct the responsiveness of small screens
> 
> <img alt="Screen Shot 2020-01-16 at 16 38 52" width="492" src="https://user-images.githubusercontent.com/45129725/72533979-bb70fb80-387e-11ea-8575-97167a7d93f6.png">

2020-01-16 16:17 UTC, hezronkimutai approved these changes

2020-01-16 19:39 UTC, NiyongaboEric requested changes
Good Job @victorkarangwa4 . I can confirm that it works locally. 
Ensure feature is running on Heroku and the footer is not jumping.

2020-01-16 20:17 UTC, shemaeric requested changes
Good work @victorkarangwa4 , you can work on the requested changes, and also work on inputs so that you leave padding (space) between the left border and the text that will be written. 

Also, make sure that after the admin has successfully created an accommodation, he is redirected to the other page.

2020-01-16 20:17 UTC, shemaeric commented on src/assets/css/accommodation.scss
> +        //   .upload-btn {
please remove these commented codes

2020-01-17 10:02 UTC, NiyongaboEric approved these changes

2020-01-20 14:32 UTC, nziokaivy approved these changes
Great work @victorkarangwa4

2020-01-21 10:42 UTC, shemaeric approved these changes

2020-01-21 10:42 UTC, merged