#1692585870 a user or a manager should be able to comment on a trip requests
andela/team-odd-bn-frontend pull request #29
Opened 2020-01-20 18:32 UTC by hezronkimutai

- setup redux for the comment feature
- [Finishes #1692585870]

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-01-22 15:04 UTC, william000000 requested changes
Great Work @hezronkimutai, And remember to work on the pop box when you hit the delete button.

2020-01-22 15:04 UTC, william000000 commented on src/helpers/errorProcessor.js
> +};
Looks good!

2020-01-22 15:04 UTC, william000000 commented on src/views/trips/CommonSingleRequest.js
> +                    value={xx}
use a meaningful name for this `xx` variable

2020-01-23 05:27 UTC, NiyongaboEric requested changes
Good job @hezronkimutai! I realized we need to do extra work to finish the work.

- I request delete the comment in real-time,  normally you would refresh the browser.
<img width="1440" alt="Screen Shot 2020-01-23 at 07 14 04" src="https://user-images.githubusercontent.com/33821734/72958602-771ab980-3db0-11ea-8281-9ba7173e36ac.png">

- What do you think if we design custom modal or find packages to use instead of using browser alert
<img width="1440" alt="Screen Shot 2020-01-23 at 07 22 42" src="https://user-images.githubusercontent.com/33821734/72958996-8b12eb00-3db1-11ea-99e4-1b568341731c.png">

2020-01-23 05:27 UTC, NiyongaboEric commented on src/containers/TripsContainer/RoundTrip.js
> +export default connect(mapStateToProps, { createRoundTrip, updateSpinnerStatus, getTripAction })(RoundTrip);
add EOL

2020-01-23 09:01 UTC, NiyongaboEric approved these changes

2020-01-23 11:30 UTC, victkarangwa reviewed
Good job @hezronkimutai 
Take a look at the feedback I left!

2020-01-23 11:30 UTC, victkarangwa commented on src/assets/css/table.scss
>    returnDate: 'return date',
Could you please write the headers in sentence case?
like this:
```js
$tt: (originId: 'Origin',
destinationId: 'Destination',
startDate: 'Start date',
 returnDate: 'Return date',
  reason: 'Eeason',
```

2020-01-23 21:32 UTC, victkarangwa approved these changes
Good job @hezronkimutai

2020-01-23 23:44 UTC, shemaeric approved these changes
Good work @hezronkimutai

2020-01-23 23:44 UTC, merged