feat(roles): Super admin should be able to assign roles
andela/team-odd-bn-frontend pull request #32
Opened 2020-01-22 11:00 UTC by victorkarangwa4

#### What does this PR do?
- Super admin can asign new roles to the users
#### Description of Task to be completed?
- This PR adds the functionalities for the super admin to assign new roles to the staff members
#### How should this be manually tested?
- `git clone https://github.com/andela/team-odd-bn-frontend`
- `git checkout ft-user-role-settings-169258584`
- `npm run install` to install all dependencies
- `npm run dev` to start development server
- `login with super admin credentials
- navigate to `/admin/roles` route
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169258584](https://www.pivotaltracker.com/story/show/169258584)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2020-01-22 at 12 59 19" src="https://user-images.githubusercontent.com/35301129/72888848-112e2380-3d17-11ea-912f-034451a47dce.png">
<img width="1440" alt="Screen Shot 2020-01-22 at 12 59 28" src="https://user-images.githubusercontent.com/35301129/72888850-11c6ba00-3d17-11ea-866c-09ed79153f3f.png">

#### Questions:
N/A

2020-01-23 05:51 UTC, NiyongaboEric requested changes
Well done @victorkarangwa4. I would like to request you to improve work again.

- Please ensure we have pagination functionality, for now, we are displaying all users from DB. As an admin, I would like to see a few users, then I paginate to get more users.

- What do you think if we toast user who are trying to access admin page? What you have done is to protect the route but it is not easy to guess why the user is being redirected to the dashboard.

- I have noticed that we can use blocked token to access admin route.

2020-01-23 08:20 UTC, nziokaivy requested changes
Great job @Victor! Very nice implementation!

However please ensure we can view the users' role

2020-01-23 13:39 UTC, NiyongaboEric approved these changes

2020-01-23 14:40 UTC, hezronkimutai commented on src/__tests__/components/SelectOption.test.js
> +  ];
You can consider moving this data to the __mocks__ folder

2020-01-23 14:40 UTC, hezronkimutai commented on src/__tests__/containers/admin/UserRoles.test.js
> +  // });
Consider removing these comments too

2020-01-23 14:41 UTC, hezronkimutai commented on src/views/trips/CommonRequests.js
> +    console.log('/////', entities);
Remove these console log too.

2020-01-23 14:42 UTC, hezronkimutai requested changes
Hi @ victor I left some comments please have a look at it.

2020-01-23 15:25 UTC, nziokaivy approved these changes

2020-01-23 19:51 UTC, hezronkimutai approved these changes

2020-01-24 11:02 UTC, shemaeric approved these changes
Good work @victorkarangwa4

2020-01-24 11:05 UTC, merged

2020-01-24 11:06 UTC, william000000 approved these changes

2020-01-24 11:06 UTC, william000000 commented on src/components/SelectOption.js
> +};
Nice shot!

2020-01-24 11:08 UTC, william000000 commented on src/components/SelectOption.js
> +    </select>
Nice Shot!