#169258608 User get all trips made between specific dates
andela/team-odd-bn-frontend pull request #33
Opened 2020-01-22 11:18 UTC by william000000

#### What does this PR do?
Users should get stats of trips made in the last X timeframe
#### Description of Task to be completed?
- Design the components
- Consume GET Request API for this functionality
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
[#169258608](https://www.pivotaltracker.com/story/show/169258608)
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/40672143/72890008-9d414a80-3d19-11ea-9aa6-1b488206091e.png)

#### Questions:

2020-01-23 12:13 UTC, victorkarangwa4 commented on src/containers/trips/SearchStats.js
> +    console.log('kkkkkkk', getStatsData);
Could you please remove unnecessary comments?

2020-01-23 12:15 UTC, victorkarangwa4 commented on src/redux/actions/tripsActions/statsTripActions.js
> +
I think this comment is unnecessary.

2020-01-23 12:17 UTC, victorkarangwa4 commented on src/views/trips/SearchTripStats.js
> +  console.log('datta====>', data);
Unnecessary comment

2020-01-23 12:17 UTC, victorkarangwa4 commented on src/views/trips/SearchTripStats.js
> +
I think this comment is unnecessary too.

2020-01-23 12:19 UTC, victkarangwa requested changes
So far so good @william000000 
However, you can get rid of some unnecessary `console.log`

2020-01-24 10:09 UTC, hezronkimutai approved these changes

2020-01-24 10:09 UTC, hezronkimutai commented on src/components/StatsNav.js
> +  console.log('statet----', state.trips.getStats.getStatsInput);
Make sure you remove the console.

2020-01-24 10:20 UTC, victkarangwa approved these changes

2020-01-24 10:20 UTC, shemaeric approved these changes
Good work @william000000

2020-01-24 10:23 UTC, NiyongaboEric commented
Good job @william000000.  I like the IPAD responsiveness.

<img width="1440" alt="Screen Shot 2020-01-24 at 12 21 32" src="https://user-images.githubusercontent.com/33821734/73062099-40be6680-3ea4-11ea-81c6-f24934286bcc.png">

2020-01-24 10:23 UTC, NiyongaboEric approved these changes

2020-01-24 10:24 UTC, merged