#170893840 Design dashboard home page
andela/team-odd-bn-frontend pull request #37
Opened 2020-01-28 10:49 UTC by nziokaivy

#### What does this PR do?

This pull request sets out to design the home page in the dashboard once a user is logged in.

#### Description of Task to be completed?
-  [x] Add dashboard layout
- [x] Style dashboard component
- [x] Add tests
- [x] Set up the redux structure for the most travelled destination
- [x] Set up the redux structure to get the number of requests made by the user
- [x] Set up the redux structure to get the number of the bookings made by the user

#### How should this be manually tested?

- Clone this repository using the command `git clone https://github.com/andela/team-odd-bn-frontend.git`
- Then navigate into the project `cd team-odd-bn-frontend`
- Switch to the avail requests branch using the command: `git checkout ft-design-homepage-170893840`
- Run the command `npm i `to install all the packages
- Run `npm run dev` to run the server
- Then finally, navigate to the dashboard home page by navigating to the route `/dashboard`

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[170893840](https://www.pivotaltracker.com/story/show/170893840)

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/45204494/73257502-88a6fb80-41cc-11ea-9549-58ea972f3ae5.png)

#### Questions:

2020-01-28 13:42 UTC, hezronkimutai requested changes
Nice job @nziokaivy , I think you should make the highlighted div to be at the center or make the div be 100% width so that it looks uniform with the other divs.
<img width="1405" alt="Screen Shot 2020-01-28 at 15 39 02" src="https://user-images.githubusercontent.com/45129725/73268961-94062100-41e4-11ea-8a27-fdc232af7a8d.png">

2020-01-28 17:21 UTC, NiyongaboEric requested changes
Nice design @nziokaivy. I recommend you to increase the most travelled destination font size and remove Home title.
<img width="1071" alt="Screen Shot 2020-01-28 at 19 18 54" src="https://user-images.githubusercontent.com/33821734/73288264-55cc2a00-4203-11ea-8e3d-ada3ea4b97f6.png">

2020-01-29 07:12 UTC, victkarangwa reviewed
Nice work @nziokaivy 
We've been waiting for this dashboard for so long. Thanks for your diligence.
Just have a look at the feedback I left.

2020-01-29 07:12 UTC, victorkarangwa4 commented on src/__tests__/actionTests/getAllBookingActionTests.js
> +          message: 'Success',
Would mind placing these data under mocks?

2020-01-29 07:12 UTC, victorkarangwa4 commented on src/__tests__/actionTests/getAllBookingActionTests.js
> +      }];
The same here, I think you can make your code DRY by placing them under mocks data

2020-01-29 10:30 UTC, hezronkimutai approved these changes
Nice work @nziokaivy

2020-01-29 11:33 UTC, NiyongaboEric approved these changes

2020-01-29 19:07 UTC, victkarangwa approved these changes
Good Job @nziokaivy!

2020-01-30 12:42 UTC, shemaeric approved these changes

2020-01-30 12:42 UTC, merged