Ft user search functionality 169258591
andela/team-odd-bn-frontend pull request #38
Opened 2020-01-29 09:55 UTC by victorkarangwa4

#### What does this PR do?
This PR adds search functionality for the users
#### Description of Task to be completed?
- User is able to search a specific record from the requests table
- Admin is able to search for a certain user fro users table
#### How should this be manually tested?
- `git clone https://github.com/andela/team-odd-bn-frontend.git`
- `cd team-odd-bn-frontend`
- `git checkout /ft-user-search-functionality-169258591`
- `npm install` packages
- `npm run dev`
- Log in to the system
- Navigate to `Users` if you logged in as a super admin and search for a user by email
- Navigate to `My trips` if you logged in as a normal user
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169258591](https://www.pivotaltracker.com/story/show/169258591)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2020-01-29 at 11 53 44" src="https://user-images.githubusercontent.com/35301129/73346173-1860ae80-428e-11ea-8a5b-c4124f23f373.png">
<img width="1440" alt="Screen Shot 2020-01-29 at 11 54 04" src="https://user-images.githubusercontent.com/35301129/73346174-18f94500-428e-11ea-8023-47b6d25d7386.png">

#### Questions:
N/A

2020-01-30 10:07 UTC, NiyongaboEric requested changes

2020-01-30 10:07 UTC, NiyongaboEric commented on src/__tests__/containers/admin/UserRoles.test.js
> +  // });
Remember to remove or uncomment lines of code.

2020-01-30 10:07 UTC, NiyongaboEric commented on src/__tests__/helpers/pagination.test.js
> +});
Refactor the test by separating mock data and test.

2020-01-30 10:07 UTC, NiyongaboEric commented on src/helpers/Paginate.js
> +};
Fix EOL issue.

2020-01-30 10:11 UTC, nziokaivy requested changes
Great job @victorkarangwa4! I really like the implementation of this feature. I think we can make it better and more user-friendly over time.

However, I have a few concerns
- What happens to a user/manager who would like to search only by origin or destination?
- Also, I think the search fields would be better if they were under the `travel request` tittle and then I think they may look better if they are positioned either tot he left or right and not in the centre.
![image](https://user-images.githubusercontent.com/45204494/73440368-d604a380-4359-11ea-9cd0-38067df2978b.png)

2020-01-30 17:04 UTC, NiyongaboEric approved these changes

2020-01-30 17:08 UTC, hezronkimutai commented on src/components/PopUp.js
> +  //     this.setState({
Remove this comments @victorkarangwa4

2020-01-30 17:09 UTC, hezronkimutai commented on src/views/trips/RequestsView.js
> +          // return handleFilter(e, data, search.key);
Remove this comments too.

2020-01-30 17:10 UTC, hezronkimutai requested changes
I see you have done a nice work @victorkarangwa4 , but there are still comments which we don't need, please remove them and we will be good to go.

2020-01-30 18:35 UTC, hezronkimutai approved these changes
Nice work.

2020-01-31 09:16 UTC, nziokaivy approved these changes

2020-01-31 10:18 UTC, shemaeric approved these changes

2020-01-31 10:18 UTC, merged