Ft edit travel requests 169258595
andela/team-odd-bn-frontend pull request #39
Opened 2020-01-29 17:02 UTC by hezronkimutai

#### What does this PR do?
This PR allows users to edit travel requests
#### Description of Task to be completed?
- Design the UI as in the mock up
- Setup redux 
#### How should this be manually tested?
Follow the following steps to test this feature
- `git clone https://github.com/andela/team-odd-bn-frontend`
- 
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-01-30 10:22 UTC, NiyongaboEric requested changes
Kudos to @hezronkimutai for delivering a feature in a short period of time. I have left feedback that would help you to finalize the work.
- +1 for making pagination re-usable.
- I have the following errors from Chrome developer tools.
<img width="1440" alt="Screen Shot 2020-01-30 at 12 05 28" src="https://user-images.githubusercontent.com/33821734/73439918-19124700-4359-11ea-8e5f-af3f8c3ffa8b.png">

2020-01-30 10:22 UTC, NiyongaboEric commented on src/__tests__/containers/admin/UserRoles.test.js
> +    // component.find('[data-test="dataFilter-test"]').simulate('change', 'me');
Remove all comment.

2020-01-30 10:22 UTC, NiyongaboEric commented on src/__tests__/views/trips/CommonRequests.test.js
> +    // const page2 = wrapper.find('#page2');
Remove comment

2020-01-30 10:22 UTC, NiyongaboEric commented on src/__tests__/views/trips/CommonTable.test.js
> +    // expect(wrapper).toMatchSnapshot();
It seems that you have many comments just try to clear all of them.

2020-01-30 10:22 UTC, NiyongaboEric commented on src/helpers/Paginate.js
> +};
+1 for creating re-usable pagination.

2020-01-30 10:22 UTC, NiyongaboEric commented on src/views/trips/CommonSingleRequest.js
> +                    </button> */}
Clear all comments.

2020-01-30 16:13 UTC, NiyongaboEric approved these changes

2020-01-30 20:25 UTC, victkarangwa reviewed
Well done @hezronkimutai 
Just check on the feedback I left.

2020-01-30 20:25 UTC, victorkarangwa4 commented on src/__tests__/improveTests.js
> +};
I think you could have placed `improveTestMockup` under mock file

2020-01-31 09:35 UTC, victkarangwa approved these changes
Good job @hezronkimutai

2020-01-31 11:49 UTC, merged