Ch setup testing 169258568
andela/team-odd-bn-frontend pull request #4
Opened 2019-12-24 08:35 UTC by hezronkimutai

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-12-24 14:10 UTC, william000000 requested changes
Good Job @hezronkimutai, however you may put coverage folder in .gitignore file

2019-12-24 14:10 UTC, william000000 commented on jest.config.js
> +};
Nice Shot! @hezronkimutai

2019-12-24 14:59 UTC, NiyoEric commented on jest.config.js
> +  testEnvironment: 'node',
We are doing frontend so `testEnvironment: 'jsdom'`

2019-12-24 15:09 UTC, NiyoEric requested changes
Good configuration @hezronkimutai. I have left some feedback below.

2019-12-24 15:09 UTC, NiyoEric commented on package.json
> +    "dev": "webpack-dev-server --mode development --hot --open --config webpack.config.js",
Webpack is configured in ES6. Therefore you need `@babel/register` to transpile. Replace script dev command with `"dev": "webpack-dev-server --mode development --hot --open --config webpack.config.babel.js",`

2019-12-24 15:09 UTC, NiyoEric commented on public/index.html
> +    <title>Crime-App</title>
Rename application title to `Barefoot Nomad`

2019-12-24 15:09 UTC, NiyoEric commented on src/components/App.js
> +ReactDOM.render(<App store={store} />, document.getElementById('app'));
I think you need to sync with @nziokaivy. She is working on setting up redux.

2019-12-27 06:33 UTC, NiyongaboEric approved these changes

2019-12-27 07:23 UTC, NiyoEric approved these changes

2019-12-27 07:36 UTC, victkarangwa approved these changes
Well done!

2019-12-27 08:22 UTC, william000000 approved these changes
Nice Job @hezronkimutai

2019-12-27 08:29 UTC, nziokaivy approved these changes
Looks good to me! Great Job @hezronkimutai

2019-12-27 09:52 UTC, shemaeric approved these changes
Great job @hezronkimutai

2019-12-27 09:52 UTC, merged