#169258604 a user should be able to book an accommodation facility
andela/team-odd-bn-frontend pull request #41
Opened 2020-02-02 16:11 UTC by hezronkimutai

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-02-04 13:16 UTC, NiyongaboEric requested changes
Good job @hezronkimutai. I would like to request to have the same booking folder structure.

2020-02-04 13:16 UTC, NiyongaboEric commented on src/App.js
> +          <Route path="/bookings" exact component={bookAccommodation} />
I think `/bookings/create` route is better. Then we shall `/bookings` routes to display all bookings.

2020-02-04 13:16 UTC, NiyongaboEric commented on src/containers/accommodation/bookAccommodation.js
> +            />
Are you hard coding the data?

2020-02-04 13:16 UTC, NiyongaboEric commented on src/redux/actions/bookings/bookAnAccommodation.js
> +    dispatch({
I  think it is notificationError

2020-02-05 06:52 UTC, nziokaivy requested changes
Nice work @hezronkimutai! Just one tiny change you could make.
Once a user has booked you can redirect them to view their booking made

2020-02-05 15:27 UTC, NiyongaboEric approved these changes

2020-02-05 16:35 UTC, victkarangwa reviewed
Good job @hezronkimutai 
Just remember to keep us in the loop by updating the screenshots on PR description.

2020-02-06 10:00 UTC, shemaeric approved these changes

2020-02-06 10:03 UTC, victkarangwa approved these changes

2020-02-06 10:04 UTC, nziokaivy approved these changes

2020-02-06 10:04 UTC, merged