bg(search): fix user search functionality
andela/team-odd-bn-frontend pull request #46
Opened 2020-02-07 09:02 UTC by victorkarangwa4

- fix pagination issue
- add search result counter
- fix user search options
[Start #171146588]

#### What does this PR do?
- Fix search pagination issue
- Fix user search options
- Add search results counter
#### Description of Task to be completed?
- This PR fixes pagination issue when the user tries to search for a specific record
- This PR fixes user search option by allowing a user to search by any key relating to the record
- This PR also adds the counter for results retrieved according to the user search
#### How should this be manually tested?
- `git clone https://github.com/andela/team-odd-bn-frontend.git`
- `cd team-odd-bn-frontend`
- `git checkout bg-fix-search-functionality-171146588`
- `npm install` packages
- `npm run dev`
-  Login to the system
- Go to the trips and then search
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#171146588](https://www.pivotaltracker.com/story/show/171146588)
#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2020-02-07 at 10 58 23" src="https://user-images.githubusercontent.com/35301129/74015355-218e0180-4999-11ea-967d-dd2353c3b729.png">
<img width="1440" alt="Screen Shot 2020-02-07 at 10 59 04" src="https://user-images.githubusercontent.com/35301129/74015364-25ba1f00-4999-11ea-80f5-72549dced282.png">
<img width="1424" alt="Screen Shot 2020-02-07 at 11 00 36" src="https://user-images.githubusercontent.com/35301129/74015372-2783e280-4999-11ea-9bad-62b0a4d94ae9.png">

#### Questions:
N/A

2020-02-11 08:13 UTC, hezronkimutai requested changes
Hi, @victorkarangwa4 I left some feedback. Also, the tests are failing. Fix them and we will be good to go.

2020-02-11 08:13 UTC, hezronkimutai commented on src/assets/css/selectOption.scss
> +}
End of line

2020-02-12 11:55 UTC, NiyongaboEric requested changes
Well done @victorkarangwa4. Please take a look at the feedback I left

2020-02-12 11:55 UTC, NiyongaboEric commented on src/views/Dashboard/sidebar/TopRightSide.js
> +import getAllNotifications from '../../../redux/actions/notifications/getAllNotificationActions'
Why did you remove all semicolons?

2020-02-12 11:55 UTC, NiyongaboEric commented on src/views/trips/ManagerView.js
> +        // disabled={!search.key && 'disabled'}
Remove comment.

2020-02-12 13:25 UTC, nziokaivy approved these changes
Good job Victor! Looks good to me!

2020-02-17 09:07 UTC, NiyongaboEric approved these changes

2020-02-19 12:49 UTC, kipropbrian commented on src/containers/accommodation/ViewAccommodations.js
> +    console.log('=====>', allLikesDislakes)
Why?

2020-02-19 12:49 UTC, kipropbrian commented on src/containers/admin/UserRoles.js
> +      const p = this.props.adminState.allUsers.users
Destructure  all this props

2020-02-19 12:49 UTC, kipropbrian commented on src/containers/admin/UserRoles.js
> +            this.props.searchInput(e.target.value.trimLeft());
What about space on the right?

2020-02-19 12:49 UTC, kipropbrian commented on src/views/trips/RequestsView.js
> +          // disabled={!search.key && 'disabled'}
Remove if you are not using it

2020-02-19 14:04 UTC, william000000 approved these changes
Nice Job @victorkarangwa4

2020-02-19 14:28 UTC, merged