bg(fix editing a single request):
andela/team-odd-bn-frontend pull request #47
Opened 2020-02-10 09:26 UTC by hezronkimutai

removed return date from the data sent to back end while editing a one-way trip
[Finishes #171177423]

#### What does this PR do?
This PR fixes a bug and will enable users to edit a one-way trip request
#### Description of Task to be completed?
- In this PR, I changed the action file to ensure the return date field is removed from the data being sent to the backend.
#### How should this be manually tested?
- git clone `https://github.com/andela/team-odd-bn-frontend`

#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-02-12 11:48 UTC, NiyongaboEric requested changes
Good work @hezronkimutai! Take a look at the feedback I left.

2020-02-12 11:48 UTC, NiyongaboEric commented on src/assets/css/table.scss
> +          // border: solid 1px;
Remove comment.

2020-02-12 11:48 UTC, NiyongaboEric commented on src/assets/css/footer.scss
> +  // margin-top: 50px;
Remove all comments.

2020-02-12 13:28 UTC, nziokaivy approved these changes
Looks good to me! Great job Hezron!

2020-02-12 14:35 UTC, victkarangwa approved these changes
I think you are good to go!

2020-02-13 13:51 UTC, NiyongaboEric approved these changes

2020-02-19 13:07 UTC, william000000 commented on src/__tests__/containers/accommodation/viewAccommodation.test.js
> +  // it('Should simulate on change paginate by  rightarrow change state function', () => {
You may have to delete these commented codes or redo it.

2020-02-19 13:37 UTC, william000000 requested changes
This is an outstanding deed! Just attend to this small short feedback I left otherwise it looks good.

2020-02-19 13:37 UTC, william000000 commented on src/views/trips/RequestsView.js
>            placeholder="Search trips"
Kindly remove this commented line

2020-02-19 14:35 UTC, closed without merging