#171180313 Improve existing trips and bookings design
andela/team-odd-bn-frontend pull request #48
Opened 2020-02-10 15:51 UTC by NiyongaboEric

#### What does this PR do?
The PR helps to improve the existing design and functionality

#### Description of Task to be completed?
- style bookings pages
- style  trips requests

#### How should this be manually tested?
- `git clone https://github.com/andela/team-odd-bn-backend.git`
- `cd team-odd-bn-backend`
- git checkout -b ch-display-info-171180313 
- `npm install`
- Make sure your `.env` file is updated.
- Drop existing migration `npm run dropTables`
- Update migration `npm run db-migrate`
- Populate the seed data `npm run db-seed-dev`
- `npm run dev-start` check API in development 
>View all bookings`{{url}}/api/v1/bookings`.  // try it when your bookings is empty

>view specific Trips `{{url}}/api/v1/trips/oneway`. // You should first create a trip request and try to view it

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#171180313](https://www.pivotaltracker.com/story/show/171180313)

#### Screenshots (if appropriate)

Visit bookings without creating it
<img width="1440" alt="Screen Shot 2020-02-10 at 17 50 32" src="https://user-images.githubusercontent.com/33821734/74165510-e22c1300-4c2d-11ea-95dd-9d1306f1675c.png">

View specific trip request
<img width="1440" alt="Screen Shot 2020-02-10 at 15 00 22" src="https://user-images.githubusercontent.com/33821734/74165577-fd971e00-4c2d-11ea-904c-4fecdf6cc419.png">

#### Questions:

2020-02-10 16:07 UTC, kipropbrian commented
Can you move the comments down, instead of on the side.

2020-02-12 11:49 UTC, hezronkimutai commented on src/assets/css/bookings/userBookings.scss
> +}
eol

2020-02-12 11:51 UTC, hezronkimutai requested changes
Nice work @NiyongaboEric , I have left a comment, please look at it.

2020-02-12 12:05 UTC, hezronkimutai approved these changes

2020-02-12 13:30 UTC, nziokaivy approved these changes
Looks good to me! Great job @NiyoEric

2020-02-12 14:32 UTC, victkarangwa approved these changes
Good job @NiyoEric

2020-02-13 20:18 UTC, william000000 requested changes

2020-02-13 20:18 UTC, william000000 commented on src/assets/css/accommodation/allAccommodation.scss
> +}
End of line

2020-02-13 20:20 UTC, william000000 reviewed
Nice Work @NiyongaboEric

2020-02-14 09:39 UTC, merged