ch(circleCI): update circleCI
andela/team-odd-bn-frontend pull request #5
Opened 2019-12-24 09:19 UTC by victorkarangwa4

#### What does this PR do?
The PR integrate CircleCI with the project

#### Description of Task to be completed?
  - Add CircleCI badge on README
  - Add mock test 

#### How should this be manually tested?
In order to test the application try the following steps
- Run `git clone https://github.com/andela/team-odd-bn-frontend/tree/ch-setup-circleCI-169258569.git`
- `cd team-odd-bn-frontend`
- `ch-setup-circleCI-169258569`
- `npm install`
- Lastly, run `npm run dev` 

#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
[#169258569](https://www.pivotaltracker.com/story/show/169258569)
#### Screenshots (if appropriate)
N/A
#### Questions:

2019-12-24 10:13 UTC, NiyongaboEric approved these changes
@victorkarangwa4 I am happy you configured CI. I think you are good to go!

2019-12-24 13:43 UTC, hezronkimutai requested changes
Nice work, just resolve the conflict in .gitignore

2019-12-24 13:43 UTC, hezronkimutai commented on .gitignore
> +<<<<<<< HEAD
@victorkarangwa4 , can you resolve this conflict.

2019-12-27 07:05 UTC, hezronkimutai approved these changes

2019-12-27 07:23 UTC, nziokaivy approved these changes
Looks good to me @victorkarangwa4!

2019-12-27 10:07 UTC, shemaeric approved these changes
Good work @victorkarangwa4

2019-12-27 10:08 UTC, merged