ft(router): set up react router
andela/team-odd-bn-frontend pull request #7
Opened 2019-12-24 14:01 UTC by william000000

#### What does this PR do?
Setup react-router 

#### Description of Task to be completed?
  - Add set up of react-router in `src/index.js`
  - Add `NotFound.js` file to be displayed when page searched not exists

#### How should this be manually tested?
- Clone this repository using the command: `https://github.com/andela/team-odd-bn-frontend.git`
- Checkout to this branch using the command: `git checkout ch-setup-react-router-169258570`
- Install all dependencies `npm install`
- Run the application using the command: `npm run start`

#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
[#169258570](https://www.pivotaltracker.com/story/show/169258570)
#### Screenshots (if appropriate)
N/A
#### Questions:

2019-12-24 14:39 UTC, NiyoEric commented on src/index.js
> +    </div>
I recommend you to use `index.js` file to render our application and `App.js` to import all components and configure routes.

``` js
// index.js
ReactDOM.render(<App />, document.getElementById('root'));

//App.js
const App = () => {
  return (
      <Router>
        <div className="container">
          <Switch>
            <Route path="/" exact component={componentA} />
            <Route path="/signin" exact component={componentB} />
            <Route path="/signup" exact component={componentC} />
          </Switch>
        </div>
      </Router>
  );
}

```

2019-12-24 14:44 UTC, NiyoEric commented on src/index.js
> +      </ul>
I think the markup style is not needed. All routes will render components.

2019-12-24 14:44 UTC, NiyoEric requested changes
Good job @william000000! I have left feedback below. Also, I request you to update PR Readme with screenshots.

2019-12-27 06:56 UTC, hezronkimutai requested changes
Nice work willy, just check on the comments I left.

2019-12-27 06:56 UTC, hezronkimutai commented on src/App.js
> +/* eslint-disable react/jsx-filename-extension */
Hi @ willy, remove this eslint comment and solve the problem instead

2019-12-27 06:58 UTC, hezronkimutai commented on src/components/user/signout/signout.js
> +    console.log('hell');
Remove the console

2019-12-27 08:19 UTC, NiyongaboEric approved these changes

2019-12-27 08:22 UTC, NiyoEric approved these changes

2019-12-27 10:37 UTC, hezronkimutai approved these changes

2019-12-27 12:00 UTC, shemaeric approved these changes
Good work @william000000

2019-12-27 12:01 UTC, merged