#169258571 Add sass preprocessing
andela/team-odd-bn-frontend pull request #8
Opened 2019-12-24 17:01 UTC by NiyongaboEric

#### What does this PR do?
We will be using SASS preprocessing to style our project.

#### Description of Task to be completed?
- Update Webpack 
- Add `node-sass` and `sass-loader` npm packages
- Add Eslint rule to accept both .jsx and .js files extensions

#### How should this be manually tested?
- `git clone ch-setup-SASS-169258571`
- `cd team-odd-bn-frontend`
- `git checkout ch-setup-SASS-169258571`
- `npm install` packages
- `npm run dev` 
- Open `App.scss`, try to change background color by editing `$body-color: #red` the whole body will change.

#### Any background context you want to provide?
We are going to have two different ways to style pages. Pure CSS and SCSS preprocessor.

#### What are the relevant pivotal tracker stories?
[#169258571](https://www.pivotaltracker.com/story/show/169258571)

#### Screenshots (if appropriate)
Use `App.scss` file to change background color of body
<img width="812" alt="Screen Shot 2019-12-24 at 18 22 34" src="https://user-images.githubusercontent.com/33821734/71420694-4cd5bf00-267f-11ea-852d-743c3cb324c4.png">

#### Questions:

2019-12-27 07:03 UTC, hezronkimutai requested changes
Nice work Eric, just check the comment I left.

2019-12-27 07:03 UTC, hezronkimutai commented on .gitignore
> +coverage/
Eol here @NiyoEric

2019-12-27 07:16 UTC, hezronkimutai approved these changes
nice job.

2019-12-27 07:23 UTC, victkarangwa approved these changes
Good job!

2019-12-27 08:58 UTC, nziokaivy approved these changes
Great job @NiyongaboEric !

This is good to go!

2019-12-29 22:12 UTC, shemaeric approved these changes
Good work @NiyongaboEric

2019-12-29 22:12 UTC, merged